import { MenuItem } from '@/types';

export const MOCK_MENU: MenuItem[] = [
  {
    id: 'item-1',
    categoryId: 'cat-1',
    nameEn: 'Classic Cheeseburger',
    nameAr: 'تشيز برجر كلاسيك',
    descriptionEn: 'Juicy beef patty with cheddar cheese, lettuce, tomato, and our signature sauce.',
    descriptionAr: 'شريحة لحم بقري مع جبنة الشيدر، خس، طماطم، والصلصة الخاصة بنا.',
    price: 3500, // 35.00
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: 'item-2',
    categoryId: 'cat-1',
    nameEn: 'Double Smash Burger',
    nameAr: 'دبل سماش برجر',
    descriptionEn: 'Two smashed patties, double cheese, caramelized onions.',
    descriptionAr: 'شريحتين لحم سماش، دبل جبن، بصل مكرمل.',
    price: 4500, // 45.00
    image: 'https://images.unsplash.com/photo-1594212693895-72eeabafb35e?q=80&w=800&auto=format&fit=crop',
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: 'item-3',
    categoryId: 'cat-2',
    nameEn: 'Margherita Pizza',
    nameAr: 'بيتزا مارغريتا',
    descriptionEn: 'Classic tomato sauce, fresh mozzarella, and basil.',
    descriptionAr: 'صلصة طماطم كلاسيكية، جبنة الموزاريلا الطازجة، والريحان.',
    price: 4000,
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?q=80&w=800&auto=format&fit=crop',
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: 'item-4',
    categoryId: 'cat-2',
    nameEn: 'Pepperoni Pizza',
    nameAr: 'بيتزا بيبروني',
    descriptionEn: 'Tomato sauce, mozzarella, and double pepperoni.',
    descriptionAr: 'صلصة الطماطم، موزاريلا، ودبل بيبروني.',
    price: 4800,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=800&auto=format&fit=crop',
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: 'item-5',
    categoryId: 'cat-3',
    nameEn: 'Chicken Shawarma Plate',
    nameAr: 'صحن شاورما دجاج',
    descriptionEn: 'Sliced chicken shawarma served with garlic sauce, pickles, and fries.',
    descriptionAr: 'شرائح شاورما الدجاج تقدم مع صوص الثوم، المخلل، والبطاطس.',
    price: 3800,
    image: 'https://images.unsplash.com/photo-1642823616615-18117fc65e23?q=80&w=800&auto=format&fit=crop',
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: 'item-6',
    categoryId: 'cat-3',
    nameEn: 'Mixed Grill',
    nameAr: 'مشاوي مشكلة',
    descriptionEn: 'Assortment of kebabs, shish tawook, and lamb chops.',
    descriptionAr: 'تشكيلة من الكباب، شيش طاووق، وريش الغنم.',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop',
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: 'item-7',
    categoryId: 'cat-4',
    nameEn: 'Kunafa',
    nameAr: 'كنافة',
    descriptionEn: 'Warm cheese pastry soaked in sweet syrup.',
    descriptionAr: 'حلوى الجبن الدافئة مغطاة بالشربات.',
    price: 2500,
    image: 'https://images.unsplash.com/photo-1698779659039-4dff50deecac?q=80&w=800&auto=format&fit=crop',
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: 'item-8',
    categoryId: 'cat-5',
    nameEn: 'Fresh Orange Juice',
    nameAr: 'عصير برتقال طازج',
    descriptionEn: 'Freshly squeezed orange juice.',
    descriptionAr: 'عصير برتقال معصور طازج.',
    price: 1500,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=800&auto=format&fit=crop',
    isAvailable: true,
    isFeatured: false,
  }
];
